name: 1p1tCore
version: '${project.version}'
main: me.kelsi._1p1tCore
softdepend: [ ProtocolLib ]
permissions:
  1p1t.admin:
    description: "Пермишн для администрации"
    default: op
  1p1t.vip:
    description: "Пермишн для випов"
    default: op
commands:
  stats:
    usage: "Использование: /stats world - чтобы узнать информацию о сервере\n/stats player <player> - чтобы узнать информацию о игроке(только для ВИП)"
  kill:
    usage: "Использование: /kill - чтобы убить себя\n/kill <player> - чтобы убить игрока(только для администрации)"